CREATE DATABASE VENDAS-DB;

CREATE TABLE PRODUTOS (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	DESCRICAO VARCHAR(255),
	PRECO NUMERIC(16,2),
	SKU VARCHAR(20)
	DATA_CADASTRO DATE
)


CREATE TABLE CLIENTES (
	ID BIGSERIAL NOT NULL PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	ENDERECO VARCHAR(255) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	TELEFONE VARCHAR(18),
	EMAIL VARCHAR(100),
	DATA_CADASTRO DATE
);