import type { NextPage } from 'next'
import Head from 'next/head'


import { Layout } from 'components'
import Card from 'components/layout/card'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Vendas App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>

        <Card cardHeaderTitle="Teste">
          <h4>Teste</h4>
        </Card>
        <Card cardHeaderTitle="Teste 2">
          <h1>Teste</h1>
        </Card>
      </Layout>

    </div>
  )
}

export default Home
