import type { NextPage } from 'next'
import Head from 'next/head'
import MeuComponente from '../components/meu-componente'



const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Vendas App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>Bem vindo</h2>
        <MeuComponente />
      </main>
    </div>
  )
}

export default Home
