import type { NextPage } from 'next'
import Head from 'next/head'
import Button from '../components/button'
import MeuComponente from '../components/meu-componente'

import {Layout} from 'components'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Vendas App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout />

      <main>
        <h2>Bem vindo</h2>
        <Button color="info" clickEvent={() => console.log("Teste")} />
        <MeuComponente />
      </main>
    </div>
  )
}

export default Home
